name: tfsec
on:
  push:
    branches:
    - "**"
  pull_request:
jobs:
  tfsec:
    name: tfsec sarif report
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout from SCM
        uses: actions/checkout@v2
      - name: Run tfsec
        uses: tfsec/tfsec-sarif-action@v0.1.4
        with:
          sarif_file: tfsec.sarif
      #- name: Upload SARIF file
      #  uses: github/codeql-action/upload-sarif@v1
      #  with:
      #    # Path to SARIF file relative to the root of the repository
      #    sarif_file: tfsec.sarif
