name: tfsec
on:
  push:
    branches:
    - main
  pull_request:
jobs:
  tfsec:
    name: tfsec sarif report
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout from SCM
        uses: actions/checkout@v2.3.4
      - name: Run tfsec
        uses: tfsec/tfsec-sarif-action@0.0.4
        with:
          sarif_file: tfsec.sarif
          github_token: ${{ secrets.github_token }}
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif
